<?php

/**
 * @file
 * Contains center_campus.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function center_campus_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the center_campus module.
    case 'help.page.center_campus':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Api module') . '</p>';
      return $output;

    default:
  }
}