<?php

/**
 * @file
 * Contains sample_rest_resource.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sample_rest_resource_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sample_rest_resource module.
    case 'help.page.sample_rest_resource':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Api module') . '</p>';
      return $output;

    default:
  }
}
