<?php

/**
 * @file
 * Contains alumni_speaker.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function alumni_speaker_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the alumni_speaker module.
    case 'help.page.alumni_speaker':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Api module') . '</p>';
      return $output;

    default:
  }
}
