<?php

/**
 * @file
 * Contains students_life.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function students_life_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the students_life module.
    case 'help.page.students_life':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Api module') . '</p>';
      return $output;

    default:
  }
}
