<?php

/**
 * @file
 * Contains side_block.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function side_block_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the side_block module.
    case 'help.page.side_block':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Api module') . '</p>';
      return $output;

    default:
  }
}
